### ISSUE TITLE
[Mutti, Kristina] Implement the Private Database and Update API

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#126] opened 2024-04-17 22:54 UTC
In order to allow our users to create profiles we must have a database which would store the users' related information. Similarly, ir order to allow our users to create, follow, like, unlike, comment, share, and modify routes, we must store those routes and their app user/app specific information. Accordingly, we must also implement the API which would serve as an intermediary between the database and front end. 

- [x] Create a User scheme (do not forget to check our diagrams and requirements as reference). Make sure to include username, email, password at least for sign up and log in purposes.
- [x] Create a Route scheme (do not forget to check our diagrams and requirements as reference). Make sure to include Nodes, photos, creator, durations...
- [x] Create Node scheme (do not forget to check our diagrams and requirements as reference). Make sure to include location, link, etc.

Deadline: Friday, 19.04.2024.
Estimated Effort: 3-4 hours
Rewiever: @halil-karabacak

**Comment by Mutti499** [comment] 2024-04-18 10:04
Connecting database with our api seems to be problematic. @halil-karabacak can you help me a little bit?

**Comment by halil-karabacak** [comment] 2024-04-18 20:30
Do we still have any issue after the today's meeting mate? If we, we may discuss it further!

**Comment by Mutti499** [comment] 2024-04-18 21:51
The problem is fixed and our mysql connections seem nice! Good work lets keep itt upppp!

**Comment by Mutti499** [comment] 2024-04-18 23:18
For now we implemented:
- Node class model and endpoints to list all of them and one of them
- Route class model and endpoints to list all of them and one of them
- A basic HTML template for main webpage to test endpoints clearly.
- A local MySQL server

**Comment by Mutti499** [comment] 2024-04-20 12:03
Okey 
* Userclass model and endpoints to list all of them and one of them added
* Frontend to test user creation and node creaton added
It looks like readyu to go! @kristinatrajkovski can you control it ? I may have missed couple things

**Comment by kristinatrajkovski** [comment] 2024-04-20 13:32
@Mutti499 I have checked your database and functions. It all works well on my machine. 

For the future, please research how we can make the database universal for everyone. We should definitely not create brand new users and routes on every machine. 

Besides that, if we are talking about the local version, I think it is perfect. Feel free to make a pull request so all of us can use the database.

**Comment by Mutti499** [comment] 2024-04-23 01:13
We merged the branch and everything seems to be working now. Good job @kristinatrajkovski!

**Closed by Mutti499** 2024-04-23 01:13 UTC
Labels: priority: high, ASAP, back end
