### ISSUE TITLE
[Eray] Navbar bug and login module error fix

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#276] opened 2024-11-15 16:04 UTC
The components in the navbar should be scaled. For instance koduyorum icon is too small, log out button is too far away from other components etc. You should be enhancing the UI of the navbar. Also navbar can be added to the question page as well. 

login module error: an error regarding the node modules occurs when you first open the website.  You are expected to solve that.

Deadline: 21.11.2024
Estimated effort: 3hrs
Reviewer: @ceylingebes

**Comment by ErayEroglu** [comment] 2024-11-18 18:59
![image](https://github.com/user-attachments/assets/4477f364-4fce-4433-bb3f-7abac59aaaf5)


There is no description provided in the issue but I assume we are talking about this problem. I think it is about the configuration of css modules, and hope that I am close to fix it.

**Comment by serhan-cakmak** [comment] 2024-11-18 21:14
Sorry for the inconvenience regarding the question description. I updated it.

**Comment by ErayEroglu** [comment] 2024-11-23 15:00
I do not know how much time I spent for debugging, yet I am unable to solve the bug on login page. I updated dependencies but the problem is not solved. Any help is appreciated

**Comment by ErayEroglu** [comment] 2024-11-29 14:23
I think the problem is fixed now, there is not any errors on the deployed application so I am closing the issue

**Closed by ErayEroglu** 2024-11-29 14:23 UTC
Labels: bug, help wanted, priority: high
